# Generated by Django 5.0.4 on 2024-05-02 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblio_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprunter',
            old_name='adherant',
            new_name='adherant_id',
        ),
    ]
