# Generated by Django 5.0.4 on 2024-05-03 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblio_app', '0002_rename_adherant_emprunter_adherant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminsup',
            name='adherant_admin',
        ),
    ]
