# Generated by Django 5.0.4 on 2024-05-05 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblio_app', '0003_remove_adminsup_adherant_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exemplaire',
            name='emprunte',
        ),
    ]
