# Generated by Django 5.0.4 on 2024-05-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio_app', '0004_remove_exemplaire_emprunte'),
    ]

    operations = [
        migrations.AddField(
            model_name='exemplaire',
            name='empruntable',
            field=models.BooleanField(default=False),
        ),
    ]
