# Generated by Django 5.0.4 on 2024-05-11 21:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio_app', '0005_exemplaire_empruntable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulter',
            fields=[
                ('id_consultation', models.AutoField(primary_key=True, serialize=False)),
                ('date_consultation', models.DateTimeField(default=django.utils.timezone.now)),
                ('adherent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_app.adherent')),
                ('exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_app.exemplaire')),
                ('ouvrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_app.ouvrage')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_app.utilisateur')),
            ],
        ),
    ]
