# Generated by Django 5.0.6 on 2024-05-24 17:14

import django.contrib.admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('biblio_app', '0006_consulter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adherent',
            new_name='Bibliothecaire',
        ),
        migrations.CreateModel(
            name='CustomLogEntry',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admin.logentry',),
            managers=[
                ('objects', django.contrib.admin.models.LogEntryManager()),
            ],
        ),
        migrations.RenameField(
            model_name='bibliothecaire',
            old_name='id_adherant',
            new_name='id_bibliothecaire',
        ),
        migrations.RenameField(
            model_name='consulter',
            old_name='adherent_id',
            new_name='bibliothecaire',
        ),
        migrations.RenameField(
            model_name='consulter',
            old_name='date_consultation',
            new_name='date_sortie',
        ),
        migrations.RenameField(
            model_name='emprunter',
            old_name='adherant_id',
            new_name='bibliothecaire_id',
        ),
        migrations.AddField(
            model_name='consulter',
            name='date_retour',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='role',
            field=models.CharField(choices=[('UTILISATEUR', 'Utilisateur'), ('BIBLIOTHECAIRE', 'Bibliothecaire'), ('ADMINSUP', 'AdminSup')], default='UTILISATEUR', max_length=20),
        ),
    ]
