# Generated by Django 5.0.6 on 2024-05-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio_app', '0007_rename_adherent_bibliothecaire_customlogentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunter',
            name='date_rendu',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emprunter',
            name='rendu',
            field=models.BooleanField(default=True),
        ),
    ]
