# Generated by Django 5.0.6 on 2024-05-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio_app', '0008_emprunter_date_rendu_emprunter_rendu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunter',
            name='rendu',
            field=models.BooleanField(default=False),
        ),
    ]
