# Generated by Django 5.0.6 on 2024-05-25 01:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio_app', '0009_alter_emprunter_rendu'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_emprunt',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
