# Generated by Django 5.0.6 on 2024-05-25 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio_app', '0010_reservation_date_emprunt'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunter',
            name='num_extensions',
            field=models.IntegerField(default=0),
        ),
    ]
