# Generated by Django 5.0.2 on 2024-05-26 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio_app', '0012_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_app.exemplaire')),
                ('ouvrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_app.ouvrage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_app.utilisateur')),
            ],
        ),
    ]
